standard_urls:
  - service: "nomad"
    url: "http://zeus.internal:4646"
  - service: "consul"
    url: "http://zeus.internal:8500"
  - service: "traefik"
    url: "http://hermes.internal:8081"
  - service: "synology-dsm"
    url: "https://dionysus.internal:5001"
  - service: "photos"
    url: "https://photos.dbyte.xyz"
  - service: "drive"
    url: "https://drive.dbyte.xyz"
  - service: "plex"
    url: "https://video.dbyte.xyz"
  - service: "ghost"
    url: "https://admin-photo.james-hackett.ie/ghost"

nomad:
  address: "http://zeus.internal:4646"

apikey: blahblah

server_config:
  host: ""
  port: 8080
